[unittest] PS-269: Initial Percona Server 8.0.12 tree
-----------------------------------------------------------

PS-7949 Fix memry leak in gcs_xcom_control_interface-t test

https://jira.percona.com/browse/PS-7949

-----------------------------------------------------------

PS-7949 Fix memory leaks in temptable::Allocator tests

https://jira.percona.com/browse/PS-7949

-----------------------------------------------------------

PS-8979: Fix linking issue using `WITH_VALGRIND=ON`

Fix the following issue when `lld` is not detected or `-DUSE_LD_LLD=OFF` is used:
```
/usr/bin/ld: CMakeFiles/merge_large_tests-t.dir/dd_sdi-t.cc.o: warning: relocation against `_ZThn56_N2dd10Index_impl15se_private_dataEv' in read-only section `.text._ZN12sdi_unittestL11mock_dd_objEPN2dd5IndexEPNS0_6ColumnE'
/usr/bin/ld: CMakeFiles/merge_large_tests-t.dir/dd_sdi-t.cc.o: relocation R_X86_64_PC32 against symbol `_ZThn56_N2dd11Column_impl15se_private_dataEv' can not be used when making a PIE object; recompile with -fPIE
```

(cherry picked from commit c75e96abb48e36307fa9d7f3da593d52d73e7a08)

-----------------------------------------------------------

PS-9071: Merge MySQL 8.3.0 (fix test_routing_direct tests)

https://perconadev.atlassian.net/browse/PS-9071

Tests lack knowledge of some Percona and debug build specific system
variable names.
Updated known system variables lists for tests to be able to categorize
them properly.

-----------------------------------------------------------

PS-9218: Merge MySQL 8.4.0 (fix gcc-14 build)

https://perconadev.atlassian.net/browse/PS-9218

-----------------------------------------------------------

PS-9328 merge: Merge 8.4.2 - Fixed gcc-12 RelWithDebInfo compilation warnings (#5406)

https://perconadev.atlassian.net/browse/PS-9328

Suppressed '-Wrestrict' warnings in selected GIS and Router unit tests.

/usr/include/c++/12/bits/char_traits.h:435:56: error: ‘void* __builtin_memcpy(void*, const void*, long unsigned int)’ accessing 9223372036854775810 or more bytes at offsets [2, 9223372036854775807] and 1 may overlap up to 9223372036854775813 bytes at offset -3 [-Werror=restrict]
  435 |         return static_cast<char_type*>(__builtin_memcpy(__s1, __s2, __n));
      |                                        ~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~